export let LOGIN_DETAIL = "LOGIN_DETAIL"
export let LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export let LOGIN_FAILED = 'LOGIN_FAILED'
export let TOKEN = 'TOKEN'
export let PROFILE = 'PROFILE'
export let LOGOUT = "LOGOUT"

export let CREATE_COMPANY = "CREATE_COMPANY"
export let PASSWORD_CONFIRMED = "PASSWORD_CONFIRMED"
export let PASSWORD_CONFIRMED_ERROR = "PASSWORD_CONFIRMED_ERROR"

export let COMPANIES_LIST = "COMPANIES_LIST"

export let DELETE_COMPANY = "DELETE_COMPANY"

export let EDIT_COMPANY = "EDIT_COMPANY"

export let PASSWORD_UPDATED = "PASSWORD_UPDATED"

export let PASSWORD_UPDATED_ERROR = "PASSWORD_UPDATED_ERROR"
export let PAYMENT_TYPE_ADDED = "PAYMENT_TYPE_ADDED"
export let PAYMENT_TYPE_ERROR = "PAYMENT_TYPE_ERROR"
export let DELETE_PAYMENT_TYPE = "DELETE_PAYMENT_TYPE"
// export let PASSWORD_UPDATED_ERROR = "PASSWORD_UPDATED_ERROR"

